create table notifications (
    id bigint generated by default as identity primary key,
    user_id varchar(100) not null,
    title varchar(160) not null,
    message varchar(1000) not null,
    category varchar(40) not null,
    is_read boolean not null default false,
    created_at timestamp not null default current_timestamp,
    read_at timestamp null
);

create index idx_notifications_user_created_at on notifications (user_id, created_at desc);
create index idx_notifications_user_read on notifications (user_id, is_read);
