create table roles (
    id bigint generated by default as identity primary key,
    code varchar(40) not null unique,
    description varchar(120) not null
);

create table studyhub_users (
    id bigint generated by default as identity primary key,
    public_id varchar(100) not null unique,
    email varchar(160) not null unique,
    display_name varchar(120) not null,
    password_hash varchar(100) not null,
    active boolean not null default true,
    created_at timestamp not null default current_timestamp
);

create table user_roles (
    user_id bigint not null,
    role_id bigint not null,
    primary key (user_id, role_id),
    constraint fk_user_roles_user foreign key (user_id) references studyhub_users (id),
    constraint fk_user_roles_role foreign key (role_id) references roles (id)
);

create index idx_studyhub_users_email on studyhub_users (email);
create index idx_studyhub_users_public_id on studyhub_users (public_id);
