create table user_follows (
    id bigint generated by default as identity primary key,
    follower_user_id bigint not null,
    followed_user_id bigint not null,
    created_at timestamp not null default current_timestamp,
    constraint fk_user_follows_follower foreign key (follower_user_id) references studyhub_users (id),
    constraint fk_user_follows_followed foreign key (followed_user_id) references studyhub_users (id),
    constraint uk_user_follows_pair unique (follower_user_id, followed_user_id)
);

create table posts (
    id bigint generated by default as identity primary key,
    author_user_id bigint not null,
    title varchar(160) not null,
    description varchar(1000) not null,
    module_code varchar(40) not null,
    original_file_name varchar(255) not null,
    content_type varchar(120) not null,
    file_size bigint not null,
    storage_path varchar(400) not null,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    constraint fk_posts_author foreign key (author_user_id) references studyhub_users (id)
);

create table post_likes (
    id bigint generated by default as identity primary key,
    post_id bigint not null,
    user_id bigint not null,
    created_at timestamp not null default current_timestamp,
    constraint fk_post_likes_post foreign key (post_id) references posts (id),
    constraint fk_post_likes_user foreign key (user_id) references studyhub_users (id),
    constraint uk_post_likes_pair unique (post_id, user_id)
);

create index idx_user_follows_follower on user_follows (follower_user_id);
create index idx_user_follows_followed on user_follows (followed_user_id);
create index idx_posts_author_created_at on posts (author_user_id, created_at desc);
create index idx_posts_module on posts (module_code);
create index idx_post_likes_post on post_likes (post_id);
