create table followed_modules (
      id bigint generated by default as identity primary key,
      user_id bigint not null,
      module_code varchar(40) not null,
      created_at timestamp not null default current_timestamp,
      constraint fk_followed_modules_user foreign key (user_id) references studyhub_users (id),
      constraint uk_followed_modules_pair unique (user_id, module_code)
);

create index idx_followed_modules_user on followed_modules (user_id);
create index idx_followed_modules_module on followed_modules (module_code);