create table post_comments (
   id bigint generated by default as identity primary key,
   post_id bigint not null,
   user_id bigint not null,
   body varchar(2000) not null,
   created_at timestamp not null default current_timestamp,
   constraint fk_post_comments_post foreign key (post_id) references posts (id),
   constraint fk_post_comments_user foreign key (user_id) references studyhub_users (id)
);

create index idx_post_comments_post on post_comments (post_id, created_at);
create index idx_post_comments_user on post_comments (user_id);